# Generated by Django 4.2.5 on 2026-08-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agency_city_condominium_country_neighborhood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyfee',
            name='fee_type',
            field=models.CharField(choices=[('CONDOMINIUM', 'Condomínio'), ('PROPERTY_TAX', 'IPTU')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyprice',
            name='purpose',
            field=models.CharField(choices=[('SALE', 'Comprar'), ('RENT', 'Alugar'), ('SEASONAL', 'Temporada')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('USER', 'Usuário')], default='USER', max_length=10),
        ),
    ]
