# Generated by Django 4.2.5 on 2026-08-01 12:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_propertyphoto_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exporter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exportador',
                'verbose_name_plural': 'Exportadores',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExporterPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Ordem do plano na tela')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.exporter')),
            ],
            options={
                'verbose_name': 'Plano do exportador',
                'verbose_name_plural': 'Planos do exportador',
                'ordering': ('position', 'name'),
                'unique_together': {('exporter', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Infraestrutura',
                'verbose_name_plural': 'Infraestruturas',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='document_notes',
            field=models.TextField(blank=True, help_text='Observações sobre a documentação'),
        ),
        migrations.AddField(
            model_name='property',
            name='guests',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='has_leasehold',
            field=models.BooleanField(default=False, help_text='Imóvel com laudêmio'),
        ),
        migrations.AddField(
            model_name='property',
            name='living_rooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='local_contact',
            field=models.CharField(blank=True, help_text='Contato no local do imóvel', max_length=150),
        ),
        migrations.AddField(
            model_name='property',
            name='maps_url',
            field=models.URLField(blank=True, help_text='Localização no Google Maps', max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='on_site',
            field=models.BooleanField(default=False, help_text='Publicado no site da imobiliária'),
        ),
        migrations.AddField(
            model_name='property',
            name='opportunity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='region',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='property',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='show_prices',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='trade_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='under_construction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, help_text='Vídeo do imóvel no YouTube', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='visit_notes',
            field=models.TextField(blank=True, help_text='Observações sobre visitas'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='core.agency')),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
                'ordering': ('name',),
                'unique_together': {('agency', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brokers', to='core.agency')),
            ],
            options={
                'verbose_name': 'Captador',
                'verbose_name_plural': 'Captadores',
                'ordering': ('name',),
                'unique_together': {('agency', 'name')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='core.broker'),
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='properties', to='core.feature'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='core.owner'),
        ),
        migrations.CreateModel(
            name='PropertyExporter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='core.exporter')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='core.exporterplan')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exporters', to='core.property')),
            ],
            options={
                'verbose_name': 'Exportador do imóvel',
                'verbose_name_plural': 'Exportadores do imóvel',
                'unique_together': {('property', 'exporter')},
            },
        ),
    ]
