# Generated by Django 4.2.5 on 2026-08-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_exporter_exporterplan_feature_property_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='code',
            field=models.CharField(blank=True, help_text='Código do imóvel dentro da imobiliária, aceita letras e números', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(blank=True, help_text='Montado a partir do tipo e do bairro quando não informado', max_length=255),
        ),
    ]
