# Generated by Django 4.2.5 on 2026-08-07 01:16

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fee_propertyfee_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominium',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='condominiums', to='core.feature'),
        ),
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.CharField(choices=[('PROPERTY', 'Imóvel'), ('CONDOMINIUM', 'Condomínio')], default='PROPERTY', max_length=20),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='propertyphoto',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Foto usada como miniatura'),
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together={('name', 'type')},
        ),
        migrations.CreateModel(
            name='CondominiumPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=core.models.photo_upload_to)),
                ('is_main', models.BooleanField(default=False, help_text='Foto usada como miniatura')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Ordem da foto na galeria')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Tamanho do arquivo em bytes')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.condominium')),
            ],
            options={
                'verbose_name': 'Foto do condomínio',
                'verbose_name_plural': 'Fotos do condomínio',
                'ordering': ('position', 'created_at'),
                'abstract': False,
            },
        ),
    ]
