# Generated by Django 4.2.5 on 2026-08-11 01:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_condominium_features_feature_type_alter_feature_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('property_limit', models.PositiveIntegerField(blank=True, help_text='Vazio = imóveis ilimitados', null=True)),
                ('photo_limit', models.PositiveIntegerField(blank=True, help_text='Vazio = fotos ilimitadas', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='core.plan'),
        ),
    ]
