# Generated by Django 4.2.5 on 2026-08-11 01:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_plan_agency_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyExporter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_exporters', to='core.agency')),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agency_exporters', to='core.exporter')),
            ],
            options={
                'verbose_name': 'Exportador da imobiliária',
                'verbose_name_plural': 'Exportadores da imobiliária',
                'unique_together': {('agency', 'exporter')},
            },
        ),
        migrations.CreateModel(
            name='AgencyExporterPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('limit', models.PositiveIntegerField(default=0, help_text='Zero = nenhum imóvel neste plano')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency_exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.agencyexporter')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_plans', to='core.exporterplan')),
            ],
            options={
                'verbose_name': 'Limite de plano do exportador',
                'verbose_name_plural': 'Limites de plano do exportador',
                'ordering': ('plan__position', 'plan__name'),
                'unique_together': {('agency_exporter', 'plan')},
            },
        ),
    ]
