# Generated by Django 4.2.5 on 2026-08-12 00:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_exporter_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, help_text='Código do cliente dentro da imobiliária, aceita letras e números', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('document', models.CharField(blank=True, help_text='CPF ou CNPJ', max_length=20)),
                ('type', models.CharField(choices=[('BUYER', 'Comprador'), ('SELLER', 'Vendedor'), ('TENANT', 'Locatário'), ('LANDLORD', 'Locador')], default='BUYER', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=10)),
                ('complement', models.CharField(blank=True, max_length=60)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.agency')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='core.neighborhood')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('name',),
                'unique_together': {('agency', 'code')},
            },
        ),
    ]
