# Generated by Django 4.2.5 on 2026-08-13 02:02

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_exporter_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_categories', to='core.agency')),
            ],
            options={
                'verbose_name': 'Categoria do blog',
                'verbose_name_plural': 'Categorias do blog',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, help_text='Destino do banner no site')),
                ('image', models.ImageField(upload_to=core.models.site_image_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_banners', to='core.agency')),
            ],
            options={
                'verbose_name': 'Banner do site',
                'verbose_name_plural': 'Banners do site',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='CompanySection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.site_image_upload_to)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_sections', to='core.agency')),
            ],
            options={
                'verbose_name': 'Seção da empresa',
                'verbose_name_plural': 'Seções da empresa',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, help_text='Endereço da matéria no site', max_length=180)),
                ('published_at', models.DateField(default=django.utils.timezone.localdate)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.site_image_upload_to)),
                ('youtube_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado')], default='DRAFT', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='core.agency')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='core.blogcategory')),
            ],
            options={
                'verbose_name': 'Matéria do blog',
                'verbose_name_plural': 'Matérias do blog',
                'ordering': ('-published_at', '-created_at'),
                'unique_together': {('agency', 'slug')},
            },
        ),
    ]
