# Generated by Django 4.2.5 on 2026-08-14 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_site_content_and_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource', models.CharField(choices=[('dashboard', 'Dashboard'), ('leads', 'Leads'), ('atendimentos', 'Atendimentos'), ('tarefas', 'Tarefas & Agenda'), ('funil', 'Funil de Vendas'), ('imoveis', 'Imóveis'), ('condominios', 'Condomínios'), ('clientes', 'Clientes'), ('proprietarios', 'Proprietários'), ('corretores', 'Corretores'), ('blog', 'Blog'), ('blog_categorias', 'Categorias do Blog'), ('banners', 'Banners'), ('empresa', 'Empresa'), ('exportadores', 'Exportadores'), ('portais', 'Portais/Exportadores'), ('relatorios', 'Relatórios'), ('usuarios', 'Usuários & Permissões'), ('configuracoes', 'Configurações do Sistema')], max_length=40)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Sem acesso'), (1, 'Leitura'), (2, 'Leitura e escrita'), (3, 'Total')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão do usuário',
                'verbose_name_plural': 'Permissões do usuário',
                'ordering': ('user', 'resource'),
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
