# Generated by Django 4.2.5 on 2026-08-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_seed_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sem acesso'), (1, 'Visualizar'), (2, 'Criar/Editar'), (3, 'Acesso total')], default=0),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='resource',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('leads', 'Leads'), ('atendimentos', 'Atendimentos'), ('tarefas', 'Tarefas & Agenda'), ('funil', 'Funil de Vendas'), ('imoveis', 'Imóveis'), ('condominios', 'Condomínios'), ('clientes', 'Clientes'), ('proprietarios', 'Proprietários'), ('corretores', 'Corretores'), ('blog', 'Blog'), ('blog_categorias', 'Categorias do Blog'), ('banners', 'Banners'), ('empresa', 'Empresa'), ('exportadores', 'Exportadores e Portais'), ('relatorios', 'Relatórios'), ('usuarios', 'Usuários & Permissões'), ('configuracoes', 'Configurações do Sistema')], max_length=40),
        ),
    ]
