# Generated by Django 4.2.5 on 2026-08-17 00:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_userpermission_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('client_name', models.CharField(max_length=150)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stage', models.CharField(choices=[('QUALIFICATION', 'Qualificação'), ('VISIT_SCHEDULED', 'Visita agendada'), ('VISIT_DONE', 'Visita realizada'), ('PROPOSAL', 'Proposta'), ('NEGOTIATION', 'Negociação'), ('CLOSING', 'Fechamento')], default='QUALIFICATION', max_length=20)),
                ('probability', models.PositiveSmallIntegerField(default=10)),
                ('estimated_close', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, choices=[('SITE', 'Site'), ('PORTALS', 'Portais Imobiliários'), ('WHATSAPP', 'WhatsApp'), ('REFERRAL', 'Indicação'), ('SOCIAL_MEDIA', 'Redes Sociais'), ('PHONE', 'Telefone'), ('OTHER', 'Outros')], max_length=20)),
                ('type', models.CharField(blank=True, choices=[('SALE', 'Venda'), ('RENT', 'Locação'), ('SEASONAL', 'Temporada')], max_length=10)),
                ('property_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, choices=[('WON', 'Ganho'), ('LOST', 'Perdido')], max_length=10, null=True)),
                ('loss_reason', models.CharField(blank=True, choices=[('PRICE', 'Preço'), ('FINANCING_DENIED', 'Financiamento negado'), ('BOUGHT_OTHER', 'Comprou/alugou outro imóvel'), ('GAVE_UP', 'Desistiu da busca'), ('NO_RESPONSE', 'Sem retorno'), ('OTHER', 'Outro')], max_length=20)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='core.agency')),
            ],
            options={
                'verbose_name': 'Negócio',
                'verbose_name_plural': 'Negócios',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, help_text='Código do lead dentro da imobiliária', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(choices=[('SITE', 'Site'), ('PORTALS', 'Portais Imobiliários'), ('WHATSAPP', 'WhatsApp'), ('REFERRAL', 'Indicação'), ('SOCIAL_MEDIA', 'Redes Sociais'), ('PHONE', 'Telefone'), ('OTHER', 'Outros')], default='SITE', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('IN_CONTACT', 'Em Contato'), ('QUALIFIED', 'Qualificado'), ('UNQUALIFIED', 'Não Qualificado'), ('CONVERTED', 'Convertido')], default='NEW', max_length=20)),
                ('interest', models.CharField(choices=[('PURCHASE', 'Compra'), ('SALE', 'Venda'), ('RENT', 'Locação')], default='PURCHASE', max_length=20)),
                ('property_type', models.CharField(blank=True, help_text='Tipo de imóvel de interesse', max_length=60)),
                ('budget', models.CharField(blank=True, help_text='Faixa de orçamento em texto livre', max_length=60)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('observations', models.TextField(blank=True)),
                ('last_contact_at', models.DateField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.agency')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.broker')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ('-created_at',),
                'unique_together': {('agency', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protocol', models.CharField(blank=True, help_text='Protocolo sequencial por ano, ex.: ATD-2026-001', max_length=20)),
                ('client_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('PURCHASE_INTEREST', 'Interesse em compra'), ('RENT_INTEREST', 'Interesse em locação'), ('PROPERTY_VALUATION', 'Avaliação de imóvel'), ('VISIT_SCHEDULING', 'Agendamento de visita'), ('DOCUMENTATION', 'Documentação'), ('POST_SALE', 'Pós-venda'), ('OTHER', 'Outro')], default='OTHER', max_length=30)),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('IN_PROGRESS', 'Em Andamento'), ('AWAITING_RESPONSE', 'Aguardando Retorno'), ('RESOLVED', 'Resolvido'), ('CLOSED', 'Fechado')], default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='NORMAL', max_length=10)),
                ('property_code', models.CharField(blank=True, help_text='Código do imóvel relacionado', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tickets', to='core.agency')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_tickets', to='core.broker')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ('-created_at',),
                'unique_together': {('agency', 'protocol')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('CALL', 'Ligação'), ('EMAIL', 'E-mail'), ('VISIT', 'Visita'), ('MEETING', 'Reunião'), ('FOLLOW_UP', 'Follow-up'), ('DOCUMENTATION', 'Documentação'), ('NEGOTIATION', 'Negociação'), ('OTHER', 'Outro')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Andamento'), ('DONE', 'Concluída')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='NORMAL', max_length=10)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('property_code', models.CharField(blank=True, help_text='Código do imóvel, obrigatório em visitas', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.agency')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.lead')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.broker')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ('due_date', 'due_time'),
            },
        ),
        migrations.CreateModel(
            name='ServiceTicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, max_length=150)),
                ('author_type', models.CharField(choices=[('AGENT', 'Atendente'), ('CLIENT', 'Cliente')], default='AGENT', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.serviceticket')),
            ],
            options={
                'verbose_name': 'Mensagem do atendimento',
                'verbose_name_plural': 'Mensagens do atendimento',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, max_length=150)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.lead')),
            ],
            options={
                'verbose_name': 'Interação do lead',
                'verbose_name_plural': 'Interações do lead',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='core.lead'),
        ),
        migrations.AddField(
            model_name='deal',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='core.broker'),
        ),
    ]
