# Generated by Django 4.2.5 on 2026-08-18 01:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_deal_lead_serviceticket_task_serviceticketmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_name', models.CharField(blank=True, max_length=100)),
                ('site_url', models.URLField(blank=True)),
                ('site_description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                ('cc_email', models.EmailField(blank=True, help_text='Recebe cópia de todos os e-mails', max_length=255)),
                ('primary_color', models.CharField(default='#003533', max_length=7)),
                ('secondary_color', models.CharField(default='#0ba7a0', max_length=7)),
                ('logo_url', models.URLField(blank=True)),
                ('favicon_url', models.URLField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('google_maps_key', models.CharField(blank=True, max_length=100)),
                ('recaptcha_site_key', models.CharField(blank=True, max_length=100)),
                ('recaptcha_secret_key', models.CharField(blank=True, max_length=100)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('property_code_auto_increment', models.BooleanField(default=True)),
                ('property_code_prefix', models.CharField(blank=True, default='IMV', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.agency')),
            ],
            options={
                'verbose_name': 'Configurações da imobiliária',
                'verbose_name_plural': 'Configurações das imobiliárias',
            },
        ),
    ]
