# Generated by Django 4.2.5 on 2026-08-20 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_agencysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='owner',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='business_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='owner',
            name='complement',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='owner',
            name='document',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ', max_length=20),
        ),
        migrations.AddField(
            model_name='owner',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='owner',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='core.neighborhood'),
        ),
        migrations.AddField(
            model_name='owner',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='owner',
            name='spouse',
            field=models.CharField(blank=True, help_text='Nome do cônjuge', max_length=150),
        ),
        migrations.AddField(
            model_name='owner',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='PropertyHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('CREATED', 'Cadastro do imóvel'), ('UPDATED', 'Alteração do imóvel'), ('PHOTOS_ADDED', 'Inclusão de imagens'), ('PHOTOS_REMOVED', 'Exclusão de imagens'), ('PHOTOS_REORDERED', 'Reordenação das imagens')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=list, help_text='Lista de {label, from, to}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico do imóvel',
                'verbose_name_plural': 'Histórico dos imóveis',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['property', '-created_at'], name='core_proper_propert_90a071_idx')],
            },
        ),
    ]
