# Generated by Django 4.2.5 on 2026-09-04 00:31

import core.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_assistantconversation_assistantmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysettings',
            name='queue_accept_minutes',
            field=models.PositiveSmallIntegerField(default=3, help_text='Minutos para aceitar a oferta; estourado, o lead passa ao próximo'),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='queue_auto_assign',
            field=models.BooleanField(default=True, help_text='Entrega o lead já aceito a quem está na vez, sem etapa de aceite'),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='queue_business_days',
            field=models.JSONField(blank=True, default=core.models.default_business_days, help_text='Dias do expediente, 0 = domingo … 6 = sábado'),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='queue_business_end',
            field=models.TimeField(default=datetime.time(23, 30)),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='queue_business_start',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='queue_decline_behavior',
            field=models.CharField(choices=[('END', 'Vai para o final da fila'), ('KEEP', 'Mantém a posição na fila')], default='END', max_length=10),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='queue_first_response_minutes',
            field=models.PositiveSmallIntegerField(default=5, help_text='Minutos, a partir do aceite, para registrar o primeiro contato'),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='queue_max_active_per_broker',
            field=models.PositiveSmallIntegerField(default=3, help_text='Atendimentos simultâneos por corretor; 0 = sem teto'),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='queue_mode',
            field=models.CharField(choices=[('SEQUENTIAL', 'Rodízio sequencial'), ('LOAD', 'Menor carga'), ('RANDOM', 'Aleatório'), ('MANUAL', 'Manual (gestor distribui)')], default='SEQUENTIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='queue_off_hours',
            field=models.CharField(choices=[('HOLD', 'Fica na espera até abrir'), ('DISTRIBUTE', 'Distribui mesmo assim')], default='HOLD', max_length=20),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='queue_return_window_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Cliente que volta nesta janela cai com o mesmo corretor; 0 = desligado'),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='queue_skips_before_pause',
            field=models.PositiveSmallIntegerField(default=2, help_text='Ofertas perdidas seguidas até pausar o corretor sozinho; 0 = nunca'),
        ),
        migrations.AddField(
            model_name='lead',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Corretor (usuário) com o lead em mãos; a fila preenche ao aceitar', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='contacted_at',
            field=models.DateTimeField(blank=True, help_text='Primeiro contato registrado; para o relógio do SLA', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='deadline_at',
            field=models.DateTimeField(blank=True, help_text='Fim do prazo da etapa atual: aceite ou primeira resposta', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='offered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='queue_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='queue_reason',
            field=models.CharField(blank=True, help_text='Por que este corretor: rodízio, regra de retorno, menor carga, escolha do gestor', max_length=60),
        ),
        migrations.AddField(
            model_name='lead',
            name='queue_status',
            field=models.CharField(blank=True, choices=[('WAITING', 'Na espera'), ('OFFERED', 'Ofertado'), ('ACCEPTED', 'Aceito'), ('IN_SERVICE', 'Em atendimento'), ('CLOSED', 'Encerrado')], help_text='Vazio quando o lead não passou pela fila', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='sla_breached',
            field=models.BooleanField(default=False, help_text='Passou do prazo de primeira resposta; marcado uma vez'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='type',
            field=models.CharField(choices=[('NOTE', 'Ação registrada'), ('ENQUEUED', 'Lead entrou na fila'), ('OFFERED', 'Ofertado'), ('ACCEPTED', 'Aceito'), ('DECLINED', 'Recusado'), ('EXPIRED', 'Prazo de aceite estourado'), ('FIRST_CONTACT', 'Primeiro contato registrado'), ('SLA_BREACH', 'SLA de primeira resposta estourado'), ('RETURNED', 'Devolvido à fila'), ('ASSIGNED', 'Atribuído manualmente pelo gestor'), ('HELD', 'Retido na espera'), ('CLOSED', 'Atendimento encerrado')], default='NOTE', max_length=20),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Corretor envolvido; vazio quando o evento é da própria fila', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='in_queue',
            field=models.BooleanField(default=True, help_text='Corretor participa da roleta da fila de atendimento'),
        ),
        migrations.AddField(
            model_name='user',
            name='queue_order',
            field=models.PositiveIntegerField(default=0, help_text='Posição na roleta; quem recebe um lead vai para o final'),
        ),
        migrations.AddField(
            model_name='user',
            name='queue_pause_reason',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='queue_presence',
            field=models.CharField(choices=[('AVAILABLE', 'Disponível'), ('PAUSED', 'Pausado'), ('OFF', 'Fora da fila')], default='AVAILABLE', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='queue_skips',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ofertas perdidas seguidas; zera ao aceitar'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, help_text='Equipe do corretor', max_length=100),
        ),
        migrations.AlterField(
            model_name='leadinteraction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('USER', 'Usuário'), ('BROKER', 'Corretor')], default='USER', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='resource',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('leads', 'Leads'), ('fila', 'Fila de Atendimento'), ('atendimentos', 'Atendimentos'), ('tarefas', 'Tarefas & Agenda'), ('funil', 'Funil de Vendas'), ('imoveis', 'Imóveis'), ('condominios', 'Condomínios'), ('clientes', 'Clientes'), ('proprietarios', 'Proprietários'), ('corretores', 'Corretores'), ('blog', 'Blog'), ('blog_categorias', 'Categorias do Blog'), ('banners', 'Banners'), ('empresa', 'Empresa'), ('exportadores', 'Exportadores e Portais'), ('relatorios', 'Relatórios'), ('usuarios', 'Usuários & Permissões'), ('configuracoes', 'Configurações do Sistema')], max_length=40),
        ),
    ]
