# Generated by Django 4.2.5 on 2026-09-17 23:55

from django.db import migrations, models


def copy_show_prices_to_prices(apps, schema_editor):
    # Imóvel com "Exibir Valores" desligado passa a ocultar cada um dos seus valores.
    PropertyPrice = apps.get_model('core', 'PropertyPrice')
    PropertyPrice.objects.filter(property__show_prices=False).update(show_price=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_queue_and_broker_type'),
    ]

    # Só acrescenta colunas: a API antiga em produção segue funcionando até o deploy.
    operations = [
        migrations.AddField(
            model_name='condominium',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='propertyprice',
            name='show_price',
            field=models.BooleanField(default=True, help_text='Valor exibido ao público; desligado, sai como "sob consulta"'),
        ),
        migrations.RunPython(copy_show_prices_to_prices, migrations.RunPython.noop),
    ]
