"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
BASE_DIR_OS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env_path = os.path.join(BASE_DIR, '.env')
load_dotenv(env_path, override=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-$ky7s$!!z%unw2_b^%6mwjl_z1estv5$svy6b=dk0854x6-fvd',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'core.User'
CORS_ORIGIN_ALLOW_ALL = True

# Application definition

INSTALLED_APPS = [
    'rest_framework.authtoken',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',
    'core',
    'admin_web',
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=180),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=5760),
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'PAGE_SIZE': 15,
    'COERCE_DECIMAL_TO_STRING': False,
    'DATETIME_FORMAT': "%Y-%m-%dT%H:%M:%S",
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/min',
        'user': '120/min',
        'login': '5/min',
        'address_lookup': '30/min',
        'assistant': '20/min',
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
   'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
   }
}




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# Coloca em português as mensagens prontas do Django, do DRF e do SimpleJWT.
LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Arquivos enviados (fotos, logos, banners). Vão para o S3 quando as três credenciais estão
# preenchidas e não são os placeholders do .env.example; senão ficam em media/ local.
# Static não vai para o bucket em nenhum caso: é servido pelo próprio Django.
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', '').strip()
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '').strip()
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '').strip()
# Região onde o bucket foi criado. Região errada dá 400 (AuthorizationHeaderMalformed) no upload
# e URL de foto que não abre.
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', '').strip() or 'us-east-1'

_AWS_PLACEHOLDERS = {'your-bucket-name', 'your-access-key', 'your-secret-key'}
_AWS_CREDENTIALS = {AWS_STORAGE_BUCKET_NAME, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY}

USE_S3_STORAGE = all(_AWS_CREDENTIALS) and not (_AWS_CREDENTIALS & _AWS_PLACEHOLDERS)

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
}
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

if USE_S3_STORAGE:
    # Domínio público dos arquivos. Aceita um domínio próprio (ex.: CloudFront); vazio usa o do
    # bucket. As URLs não são assinadas, então o bucket precisa de uma policy liberando
    # s3:GetObject em media/* — sem ela a foto grava, mas não abre (403).
    AWS_S3_CUSTOM_DOMAIN = (
        os.getenv('AWS_S3_CUSTOM_DOMAIN', '').strip()
        or f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
    )
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    # Bucket com "Object Ownership: bucket owner enforced" rejeita ACL por objeto.
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    STORAGES['default'] = {'BACKEND': 'config.storage.MediaStorage'}
    # Absoluta de propósito: com domínio na URL, o static(MEDIA_URL) de config/urls.py vira no-op.
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

# Fotos de imóvel: limites de upload e do processamento da imagem.
PROPERTY_PHOTO_FORMAT = os.getenv('PROPERTY_PHOTO_FORMAT', 'WEBP')
PROPERTY_PHOTO_MAX_SIDE = int(os.getenv('PROPERTY_PHOTO_MAX_SIDE', 1200))
PROPERTY_PHOTO_THUMBNAIL_SIDE = int(os.getenv('PROPERTY_PHOTO_THUMBNAIL_SIDE', 500))
PROPERTY_PHOTO_QUALITY = int(os.getenv('PROPERTY_PHOTO_QUALITY', 80))
PROPERTY_PHOTO_MAX_UPLOAD_MB = int(os.getenv('PROPERTY_PHOTO_MAX_UPLOAD_MB', 10))
PROPERTY_PHOTO_MAX_PER_PROPERTY = int(os.getenv('PROPERTY_PHOTO_MAX_PER_PROPERTY', 20))
PROPERTY_PHOTO_ALLOWED_EXTENSIONS = tuple(
    extension.strip().lower()
    for extension in os.getenv(
        'PROPERTY_PHOTO_ALLOWED_EXTENSIONS', '.jpg,.jpeg,.png,.webp'
    ).split(',')
    if extension.strip()
)

# Banner e seção da empresa ocupam a largura do site, então cabem mais que a foto de imóvel.
SITE_IMAGE_MAX_SIDE = int(os.getenv('SITE_IMAGE_MAX_SIDE', 1920))

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT Authorization header using the Bearer scheme. Example: \"Bearer {token}\"",
        }
    },
    "USE_SESSION_AUTH": False,
    "AUTHORIZATION_HEADER_PREFIX": "Bearer",
}

SIB_API_KEY = os.getenv('SIB_API_KEY')

URL_FORGOT_PASSWORD = os.getenv('URL_FORGOT_PASSWORD')

# Grok (xAI): modelo de linguagem usado pelo assistente Theo.
GROK_KEY_API = os.getenv('GROK_KEY_API', '')
GROK_API_URL = os.getenv('GROK_API_URL', 'https://api.x.ai/v1/chat/completions')
GROK_MODEL = os.getenv('GROK_MODEL', 'grok-4')
GROK_TIMEOUT = int(os.getenv('GROK_TIMEOUT', 60))